const multer = require("multer");
const path = require("path");
const fs = require("fs");

const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    // Check if type is "profilephoto"

    const profilePhotosDir = path.resolve("assets", "profilephotos");

    // Check if the directory exists, create it if it doesn't
    if (!fs.existsSync(profilePhotosDir)) {
      fs.mkdirSync(profilePhotosDir, { recursive: true });
    }

    cb(null, profilePhotosDir);
  },
  filename: function (req, file, cb) {
    console.log("here is the file name", file);
    cb(null, Date.now() + path.extname(file.originalname));
  },
});

const storageHandler = multer({ storage: storage });
// const storageHandlerVerify = (req, res, next) => {
//   console.log("taagroba req.file", req.file);
//   if (req.file && req.file.path) {
//     console.log("here is the req.file object generated by multer", req.file);
//     next();
//   } else {
//     console.log("file upload failed because no req.file exists");

//     console.log(req.file);
//     return res.status(400).json({ error: "File upload failed" });
//   }
// };

module.exports = { storageHandler };
